[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "a87654d5538dcd70611cc2665dce8e1c2622bd11"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "79b2336abcd39dd59fba774d0579730ef270ca264129c25296d55fa5d64a4f2a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "42aaf9e68176250ebf5673bbd80ebe84848c6676"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1fdeaf96c6e4f6b76ef963e3ba55cef1fda9b59faa283daf931ae645e0fceb11"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "6eb7d00ae5dfb434ecb5fdded969fc95ae874101"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "48d9e783161167e0c3e1cef97804b316d16ab623c24f571b3177981833660ef1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "49a8eaf1de5e162788fb440425f20c5fb63f964c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "278067fe78c6fb1ee46eaa2b1e06eaef7e7a606b9122ef0ca8a7731c358dcee9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eebe4943cb6894ea399fd94eb98f040f56a62ac7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "49c590e3d1ae3bccc09d4ac949ee099d81acc49ba535490d64bf1c261762e670"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df68255a322db4687c9ad7c513cdd76e127c4911"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f55d0ce0236cbc90b3f59ee1e94a9c49ed65aca2ad23fb60ce8426e514b5c139"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67bad3fb33f027df397f2f4b1d44ca9f03e01690"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a8fe7f791cf13c71490afa6e170ed37a8076c1de45a0c42be6aff7702fc6f8ae"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11d3fcd3f54311c5a6250b02b2d0020a3a524b7a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1ebebcc275b44edf452aa78193a54be6b264539f721802183f0be73f566689fe"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab2cc3a81d096097e576ce0815a2f1e2ff001602"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0aeddbfecdf72a75d31200c9a2970be96a40f7d3d288da68bc3c112c4a42f977"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3883261d5359ce27b70b8789753522cd87361f58"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "bb69b9e84504009043997185fdf60da11c6845f8308c576d3419fed73d9ffaf6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "af8dc0193354a2b774102c98d568e4f5ae485637"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c3421b339da3bccc0a206a58e3473aee7250ebd5bfca52904cb5a0349926679e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "0c21713a3e5915d3d7ff324ac745c13effef9a0e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "82465b14e6da5954c598942a6f9c433695157b04399fa909f687b476bb2aa1d1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "67f85bed06eb7c1f499526725cbe21f8c2b55d7f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "cfc247b996855db040ac6545b41edc9971b716e9397c1cc3c1bc081576130550"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "0bd7a3d96111f52c104891d24baef577192f536e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "942d050f4968063baf4b757829b1f55f706e124e9f7c8feb897fb179ddb680ea"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "fc00dc7b1463e84e9f13bb7f78d861c279715ced"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "2ecf099f705ceed05dff4fe62b76f605160ab91af0a01a2a79be6b8769580b94"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3ebd3bf9d72a1194518f25eaaf08bae2345119f7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "8218529df938adb003282c675d1a420b89399341853f301355d4ac7a942ccabf"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "9fedb97d75ed2dc5e3cddc9af1febc313b1191ca"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "9590f31450a2eb24994b5b9d1222c396aec1e8ca6810daed1a8ccb82ce80dd80"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "5170157460ae5c806dea8c4abd72269eb8701df0"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "29cbce601b197578d1d4f8682929bb95b6b1fc1a96cdfa83953a617a32a5388f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "a77af21b608f6c927205a24f091dd2d4e10419b1"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "5ee31cb55362af608db7aa7e124e47cec7bb01bda15fa8daa7d8c8658d53bbc9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "ad0edae68b4f1872d2d7157f888564d39fd2c673"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "b76da29253f9400905de789e8e471c4a28c7805d3e020378302fbf7baab878a2"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "dea064b945e947d48c691317f5a481268c99b439"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "527c2d4feb12165bf866fb7978abf8cf718e0d7acf8be0e226af43e521e4b8a4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "8a737b75f89ec7337ae924d1b1bbbfcbeffabc96"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "cdf810c12362c8e52a810491449f9c207f4261785e690f5bf1cbd0364b017a79"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "6f26c0ba0710fe26b648652c62ae18c91994e313"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "21472117b3128df6164048abb1d29784d4f6b99d74e1c035682792b83b674392"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "dcfa115e4439dcb2e24beadcb54361c4e46318e0"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "f6fca9beca6506777b1cb0bb957dbfd07b04126672107511c9d5040611a907c6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "ff642643052fbe1fb4582a07943638818da0eed9"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "87a36b655eb8e8f300c6df2cda721d20455697039908cd91d845723c9b957b4f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "69a502bdcb4aa3b4e6da258221677f2feca9e9c3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "4bb612fafe6d52d0dd8e7e440ecb8caef9e562fc11d2f13d3ef80d7ce5686cc8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "c9fff7431f7217e0ba4d9e7611994479d5c07ca6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "faa6cdf2c2577087cc34655baa89c57fa2665eed7e285515ca1d72db6b886375"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "213dc8cb3a531a2bd9348d17e43e31b03400162e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "27d2a866df6f3580aef4c0570a7fe45958f094e960ae3bfa16e8ade277591dd8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "aab82ee90956a94d0212d759efc3d3eb49bfe925"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0358eae93667e602c1886f211a8be1a3e6e0d42b3ef8202ee920f503ea19d220"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "2369be8e594309b78e6d5220e0ae9dc966f14475"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f17f22f90c5324d817739401a6ac175ee16e37be59d43d33535f0b5d3a31a755"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "faa634130c95749330d13609115ce00b69a759c5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ce91ea2f977d6e611f1f28430850d9e78292a3fb41c47489c602a40b11e34f67"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "be792b1df592e0a61019bb2760e113326095475d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "d4bd43a40f94ef7bdb43ce3a1a5c31f2793522ba25e04b9f211d32b55223d6cb"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "ae9ba5fdbc2cd2c362e62aac0aadedd24646fd64"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "4bbb04ad46830828dc513c731f6f6fa4727f3f8dc558b4f5c4f2db17737d4de8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "6fdc6a42b50f5a3ecd73d7ba6527e9b2cf1bbc12"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "7d13652fce9b9ee25889951cfe974e8815ea564bac493db6a1c077fb42ff025b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "befd5f6f2886cd4f781e77acdb730737159833d3"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "06044f38058b2abbc21d09b469ece85b3099a6c97332659cfccce86308e5cd05"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "a87a1430a520fb2c26516e16062b5b3827f8b6d4"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "5c459c731bf0bdd82ccbb6447a848d9796c0e70d948c4d5aff4202326f08b63f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "772bb931cfca1ba75f68c2a77826aa633c153786"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "c1db38ed464adfab6e6880a53bf178f6a9534822dc60bc12c393b8048cf77fac"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.3.0+0/HOHQMesh.v1.3.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
