[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "fdfe67e40b39a0f97acaa70f127f62585bd469e8"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "4a28ce9ea9286f35fd2f1c56a47a0399f4718c4ee718170ed7dad60635a6d718"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "19cdfa397dac990d5234d91f1f17726bab3241bb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6e9e0489972a17e145f823b25720cb113c67918df3e34a9f4f7b398501e94570"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "0691669917e52843914f066388adfe02c70d531f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9bf0de56f29c63d67196ecc3ccc480ec0046989f5ebcd2b4a641e7edf34eef15"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "e49b1f79cd125ee870f55b64be4bda7c48079449"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ed79bf8b4aad9f757cf5505a929af09b3a4a2c847f1f43eddde80b7a144cc2fe"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4444cf697ca197902bc897cf915427474f6b3035"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "901284612646699fba7963946917b7aad548b53f9fbec5ae4d550d2fd95ebd1a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87729fdd177886b705a3a1734d39a4268061cedb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5a2c1ceb3439e69529b98cc1b6e7898b777b3a33c1b3f9a7aa5746f09d7bd5c1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b51dbe3953ff59a590866c1d7143f308380f61bb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9e834c4f83a512f5b5e5a37a4c2cbb6440681a060100383edbf2b954657c08f1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c5cf5bbd4390eb7128d585f40cfa5a0faee756f8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a297582805556d416410b108a04caa68c9f5959225ba8c7ff26a5e20001af78c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "02e111c1cf1dc187a9a8669c235ed3ba65f721a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ea5aa7c1543831dccd0bb1d75461f946b3bb78b6c180f58389210237bf710a0b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b0c700d4ee6ac6984fa0356241c6f6bd4b8380e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "252fd5ba304d176a82c865ba42ab685c146af15d94d0ed6925eaefd3f747f2aa"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "fda32775d459ca443553914e1c57decc92e5d0fb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c7231a04ede91de88682d132d9fed6437ad7a96751e2c7a03d8bac60ad527e5c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "058310a75d5ace28273d6d4007bba13dcf44d558"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c54807895001bd01ca60483089c6cb6b35e9f3eea4a1982f2b331b95ed5a185b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "9317b3f4f3f179bc59e5ae1e488efc5ee1ed2cd4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "220011b50ecd8811307a8b5da99e1cac0ca0c53e48082b01382ddff8ed497198"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "f387bba910db7c6b84c8ad93e2530c426bb3c571"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "3f5eed8216d1be2c985c03ae4b46e4812f1cfd655512105169ecff7cd290310f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3d55a1c26b8b0fcafb590d76b264694721d04f0c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "4b79d5a7a69a02716c673759835dc4e840bb5eac5e2d177ee858ec781eecd839"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "dd724a8e30127c63b1e73beccb3332668301ee20"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "00dd559fd9cd8ae103c75e21e0499db33bff185a5668cf7aea373f19d0b7a063"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "ccc69f869ed5bc28011e28883fe083d748c1cb7b"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "0fc20b2ab397c157fa884d33c6154c779fd8a430a74020cbe8c6b3692767065a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "8dfecdb75c006cd4e5beccc8cd132412296da109"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "84b2dcc6070ed3d54be6ded4bdca83d4410f4e1216e6446bf9fb079c8f12eadd"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "e3c81adc3bd6c84c82776ed7b77c4e86d8e9f077"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "eb056a91d663e0bc4dd57627593687c130019b1dfacd212736f2faf4765016e4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "44bd5a2e4da5c57b30a98d51c6b860ce0d8db46d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "16be0ce8cd4d8bae8b8767655b7794fb6e50bde73f3c2f4d0417ae790a676acf"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "370d2512789ba938c666196ef251a5ce4d1e0437"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "45dba3548d9f85f7a3f85689bd085538eee3bb172cb5abf45aaab06987955e6e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "840f9b7940ea998504d420ff5259bdedb7378620"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "06bb8cdbd9f6de8b63d47b419a96d69cd8ceef16ec8f2bb6419b667cae117b57"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "746a8577883388a56ae8f30a3a0826c5b0f88506"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "39f574e04dff01f6dd8bbb80194dcc2316f04a12c04957098a82c713d3023ff3"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "bb50e106ddb853172722494c8aa4b09b43d27012"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "b32cf813bb3c02b230cf7141b8966012cb8f3674f410b7c1a9c73a708aeca45f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f08ce3547f5e9f305faa9c09254ff85a10612cad"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "e5abe1a3a4824e0ce4749c3f947713930d629222c91e7f254b8cf457e51b0485"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "91561f99bfdaa836cb201615a7b599a0a7d78330"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "af4fc8448ee0885b7e8ba5ce62e17f3244d4e784210ccc11843b4d200149dba4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "cdc07ffa2ddf08ecf85ea9994275315be45db1d5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9fdbbeb4ca3d89ad227c571efa2889e37efcf43e5bf1d35705f3ed373a12477a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "060b9e56991023d6f0faf6b389d05d7df715c47c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c2164fb1a4a2346979e943d8e29436c61e18eeebdeea7ed6ad23d5448dd7b7f6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "4293db10172bd8c5521ac78deecff1f7ddc38703"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a9c8af43fddc36840747f87cd1ed76cbf8e9958f408556281b2d6ff8573ada67"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "dcb594e88d61b802da403575c79d4dc398b895af"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ef564e0219136e435fcaa920adb3ffd89841702ba5619a6c3023bcbff3a889b4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "d7c5dd86dca2ed3b151a9a67736f329a0332fd02"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "00935427d8d3d3ce5f22679aec1f25e1e8bf2e330266153dff02082dde0eccaf"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "41b9bec755d2286675107fbc43d320822e902261"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "304ab10605db620c76be43ba9a329ff3aff2f8d77445dc442b31081b69f5ec91"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "bfa44fa2d68eaf5e17a27da3b76c79c06a762ec4"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "a4e3da6a5b81ba9315e876befec482088206f8fa354304cbcc6446f9e0c2cf92"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "4800cf5035626a242a4015b64af487aeca49080d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "c70c18c545edcc8fdbd1144b0d41a88ae4ebc7129222aea996ed4fe1256180a3"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "898a833565c1a19f50773b949f5d05615d68a522"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "b65e5edea9c6847bd4d58d657e9cb706c94967ea89253f438730527730efc76f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "d602b7bd6d073c34bdb10c892220812b015b127c"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "069e1e8ab485a900b60d8554e251a448f5fcc54697eaa95d9f700da3e5b370e9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "6e49dc3e766c9869ce2162e435de32e0330a8418"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "4d17698bdc5b5a4d19c6e4039f9e98b75fcd0e3bc164152bf8c0d887db7a7b2c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.1+0/HOHQMesh.v1.4.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
