[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "e619a29a07cd2ef1f9e9c6d6e8576c7de32f872d"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "d9811e25e0c193acf29d6b362935db8660224cb53dfa6575f93329be1458ec03"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "4844b01a8f299a66f5d08bee3b80b5c81f45426d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "826366a76037e64dbb03f5b525764e1cc5d326d01c1b639c91dc9915599a88f0"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "d33e55ff48b4e262c9ef31e415e7888077dc8e80"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "68b3498b775eb2c0bff860863faca626a11012325873716411e9828356f4d327"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "b8d0c3a761a0c96cff40bcd0ae113e539792da65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "23b2690685121c1e76042df438dfeb5e4ca8017e80b9d84434e2ddc724331166"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6c3510de042c646e94590b907d91a174fbb4eed"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "92edf0d8b323b42b837fde2216ee4302ce8ab5a0aa2ef39c2418df0678165ae1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "319ffa4c02e2a59c214105a647ae7994b1d10c0d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "8e86372ae626717b623f6d543c5dc3e5de01ebc24cc49d0513123fbbf88e226f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c817d4aecf0b933d2a5892a3b774644c1b7d9c29"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "89404a8f5c434dd99f9bb36518223ff060d634ae62c37310623f014d71f05a21"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2764efe3c4840ebfe61d22ab03b856c098b7dd5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "7b208aef78e1d172c4d251fe1b2632af9d6ce205a1b36346266e260bcecba315"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50175a609808082be3627d608497631405e73458"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "d88fbbc465522833801f0aef29e64a3245ef2f4448ae02bf764edaa5b1795c03"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e655cfc02028a1df1eb4fafd1f5341a4c6ea9f3c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "3497fddd287987035973743e2fc73624fcbbaa5edfd2ebcdb848b3e07ad7fe36"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "5210256c3bb1782bc634ace3a10c209490f8e90c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "01e36e28ec0b86590a932bbbfd3a3f535ed0909f8b83b72621439b2b106589ae"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "9eca47bd34a1a7ac57d22cde0e323b10d3c93278"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "e04fedca2606c6287323a11ceaef658dd9ef2364e178841b9aa98fe593fab219"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "1545a287e47f818b77d17d73a96954e7cbd419b3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f6b34095ef64a83dc4d748defd8217a06deeb49ca922b4e8ebd62feeb2eb6245"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "fb5d879f9b6453f73273d9702b36888c54cdf991"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a04616a05a7c3319f87a6ff7a32cbc3f7ab45ae7aeaa98aa0d04f07eaacd9a45"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "89c73ac123b551755bd4438be7aa7b1685772dd2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "17172dc871797d345e05c2744aafd5d997684aa77ab1c134292167c710071e3e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "e61f2f9a344bb944147ebb48f8986e5e849693ed"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "59f2568096062457e5b4c889285ddb3ec83842d425e7255d39cdfa871562ac66"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "97b7cb18ce12a9b97d074a567d20b5f4df77ad96"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "a3922148eec40f6ebcf6ff19d1f3680b54de6e418af46a3b7af923867b592354"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "91544fef54b26a6c5d3e029c215b67a535b0dbf0"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "987afd602751102440c614cffa02a22497304d4dc8a2e68cc9eadd2ce6b746ee"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "a92bd059aef887bf8af22008811c6634bc0bb5a6"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "c13b74b47df7968d3e737b2c79f33dcc754297a8114acaeb6d6f0a34e837598b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "8bf6fff27cfceef08173474a00bcde30d0d6b46b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "abf5134e83c4054b768dc97919b0ce621d39c4df8c1e1fb9ea6fe51f7beeee4c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "0cddd463fa2147f334b28caa8ae29affa55f0ce2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "434bd9ca305441a34f5e3eff7adc55079352a69e0a8a4cc14395e43fc063af9e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "fee28d46acecaeadb4be60ef9a17a3c2b35e045b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1ef74cb4ebe65ab76e43de5eccc27e00132bbab35bb8252b04f6a35782675e18"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "fbceb6d24eb6fdd24764081b68fe2c20abc4e418"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "86896d95b333e0286bf0c4e0ee2c67af994e5306b65c7ccd2c8b45681389ac62"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "d32776fa9b191f3ac17d5cac24cc51879d3920cd"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "fe0c7d65030d8126dc55e3f6889b97f8d4e83f427a0d4089ebfe3dc9597bcd1c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "d8f645ec98990956aaadcf0443810b580738d9e2"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "d5b7c63fa418ce4d41794468676b368648b6cd6871ef973761f6c7312b90f495"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "2759fb8a602ca048560acedece1763ddae6ba7a6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "675dc49f55a7d71ee7aab24561558e76b80b8686772b554aa44a8a0fd5650d5f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "1fcb5bb7b9e4e00adb7b6ddacf51a8f315bcc4eb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "871339372e512db3a65962e6faa64364473088e9a6f4ecca5cc21560370805c3"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "68f918929670e431bdb7025dead1ab7a2738acac"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "24ed40629d26cd95bb8d15eb0eb8e6c47233ffae24b1cddd777868614bd43670"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "e48ff0c073508efc67d206ae2f90e2ae9a692479"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "eeeec7260d8740f2efa765e4e1cf6c0f5f8608cffeab4bbfdf09f23c18f243f9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "723abc4f3b08337e0f4bdeee4df0a915aa92ec54"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "41f958a5a6b786ad63d02614dceaf854b51ccde9748af9561d2196fb665bebdb"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "c4a1ec0c99d4cbe59ca5c07fd558d5a4b2b40101"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "48346d9724c3840ba35a9797036386849b35448c6abed609881e34f617506759"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f081aa5934dd811a0526ac85ed19f7aa7e4db34e"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "d268ab97366b2f86e3155eb9be721d2e161bf13d89bec732d67cc513b12d44b5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "bf9b4e61c6f82a9b3cd0f6744e7524e9f02473e3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "ae2648adb1abf7bd0e657dc3380d16cd178944d3592a3c04f273c45897d5f2c0"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "39fabf0cd32560f30a601e9121b0a29011caddb8"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "3962e09111debb77e0e55ea089edda1513961049b8aae92687dce77f00186377"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "3069c1a000443c8de0ffa83b4e6652054af1c96d"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "58628d739b19d8070e922915c6d1ccdd620f1548d8b224ab971d5fec20810f39"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "5b2e3da4d08245805f0ea7c89dcf042ddb6d2219"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "7dd639ff70610a26a9d34c00f234b7a6c3614448655dcd379cd490a1202cef41"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "eeb1d9a79e8886940d62abeb494b4e1ea711149b"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "8df67ca1f2c2b79d7b052597048429afe1d5c6b0ab916384a2cbd1c6763ec63a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.2.1+0/HOHQMesh.v1.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
