[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "d1cb8b8cd99ba6987a9d0b47e4542d8810f31d66"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "b6fc1be442c1513380ceb9f9db19b1bf5eec814a3769c6fe1b558025baf87390"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "5d746b54c0fde86d3521c57d5199867e7b262891"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "b6a32a53d32778ea1488abf54ea0a9f8fe9d1c5cb33fc4574207a8305052ec4c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "ddb077c291e4d4e08a278b9ab3797f48486b43d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "568938a226f866eb2e3d084494a3c9ecea08e79c2f28000ae1950a338fcc9e60"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "b99d2befc36be6a59d27fb77d7878df11f428039"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f6f517a1f34427fce9fd6487f0f450a8b772a5997ef8efbd1e81b5dc741febd7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3041e144dc02cf2bd6e4ec0bf6f673a6b9f3f88"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "8e3312372e3c098365f054a53fdd7a83ad10719b224e455ea6832713126152a5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3e386141763e695c255bbb8a7de5e6f1d4242af"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "dc69b5d6c38cd3519a071b422b7ec247a16915ac19ca022c9f6d340a0e293218"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f21a3687f823b21f0f61d65efe7543793e1aa84"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5cd94b1cad952b82e34439c06ed623980f90d9beeb3c277169c1282478e4c63f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc10c34b082e7aca14a8c3cb92bb9e9b88a0d04b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "e61a43bb92fbd35d7ae78bc7812b6b3aa60044e7ec51dc0fe92fc689570e5ab2"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8ecfc4b75e2e05b5164c6adf58547c375373f66"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0c1fed21f5ac1bbef15d9501569fa1c4069ad39c52557538a7e704d70561ecbe"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b372d5cf83bec1edb9542e4fe911f4430809e00"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ebbafb5b9c067f8807b2da6c9e0b2e2b5ce1b9999d4adaac3f93f848183587e8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "9293f90c40e0858ff9b20888e3c8e80bd3bf1b17"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "e49e6abf30ec49e45cb4e1a5e571f6a65c40c4b360d4165f993b13efbdb214cb"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "1e7fa2647df6e822487024175b106261814fcbe4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c7156821cae403aad24e61462647d5969b1e958b3be22429304b4af0a2fa0024"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "06ffa8d4a963311c745cebf5935ecfd040b562c9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "056ba1f04ea35d53c5d02606f03409a5f634cca02dba2a9622107a2e9c7859a6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "04487b4595460849a6801a87ca5abbc1c4078fae"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5514b4877d552597838b28a32db9e02167834512264093988c1e925f486a81d3"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "139ff0edc4c3ff865f9029a9c4c71d5e27df4a66"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6d01906c073d9292e805ef23fe5d51f99c47a1113e44653f8440e12e21ed5c3c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "64caceec5027b2fba8a63555247879857e3d6165"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "248d6d94bcaca986bfca6baf67023639e86b86ccbeff2b58c494f8d3a28e18c7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "bb096454cccc3f5f1e847cefeb7ed076012bd5b0"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "69e753acbd5092781cbd7febdb6d47b59177dd9786a34b45d0fb4b102e3d1531"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "d42109bbd798085a5ed5e849991286ef42985237"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "f31a024f1508675aa5a38a68e785f2c0d57b3d2512cac78547bbe51490d17953"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "044d13fd2226af953c20b97bb5386d0b7bea3ddc"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "ec51c4bb97326a8243294a5fddc6ab4d0449e8433012c7cfcf9cd826d1e1823a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "9d544cfee351b78237b24a317243342401184d18"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0263036a323b55f99549b89b50a168d9ddda03fd2c91cf8694a018a4c640e2c8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "60e844300af1047289d3a0cc9d195f883f4713d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "71588ffe8d2bd3c8ddfdf971d049a5d6dffc19e4841d54bd5c8f8974a17126fb"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "b27d521b66159a9730075013f7b87ebf3dea3a23"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "fd0b72ab3f0ec18bbacd13f5776e6846dcfab98f4f01ddd5ba3fad9c365c5a07"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "59b4f97cabd7c9514930b51b62c4a4ba7fc5e60d"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "85d4c56307ba809707e3290f1ed4c336bf8d22b3343c1020101c4983f7dea0dc"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "b75952ad1dd52485be508b4c8a6b41006192f3ce"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "8a8f361bce273019362a6de53b20dfe327e605945d66e077aed3b386897653ba"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "eb00d9152e2b45c6e8cc64bc7588d70300da49a6"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "baa625f6591b023d3924e8f8ccdd2ff70353cc5e57aa713425d7ea796242cdcf"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "ab6fb3fa820dda1dcf7211231762471b03487424"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "2c6f3d0eb8a35ca31e12f771d9e6a9216a594fd28d2058a172c21798dc447b2c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "92f60c079d9564442b0deeb5ce9e1d17a502bbb3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "8b18c27a598295a0fee89efdf128b43b08fbd438d57fe94fa6c8ea1d4a05a810"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "ea0d83bdecdbb7552ac083cc23d77ac2b54ed629"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "dcc6ec058278c5fc8e489044de8cb4a52b9d4f7afb7fc5c6a94a9c0c8de0a201"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "d5c30694ecbdfee95112c6fad8a713f720c60b97"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "24e2565f8c939ee0dcc3571987586f241671058e9f5122535a7faa5d4c3e0608"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "fb3904bad801d614eedc728d3b74e8da72991d17"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0b8bb77472c7a4a7e55b241b60c41db383cb302e80c844bcd0de150de9a3df97"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "0affea3cea72a6d1b8bdb5d38463951c48b8225c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1e82424c02ccbfa58c6a6f5e5ee75d8763a8501796988cbd5c240ae409995806"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "73358abdd9ce552f806a8c323570daa6477c1658"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "5f32e677ff007e9f7988e417aa9802ca4618ab53e33517a79c4372f742f9942e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "70c2ce00f6ecdc607aabf155047e070ee69867c0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "9d6cb1d9761a9d063c3532eb0c88c71266e4de86b6894e79d30704a5fcb14f30"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "0584a3618cf0a8bd1d8dcaa003b7743a9767303d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "8ef31707af7f1509134bd82591a42b69f4b660265fbe7abe8334c71c1b2f07af"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "76ad0d049342e27492b93d51ada2299f6083680a"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "48439039aaf7584465c6465c8c177d14163d052ac32bc45794a892973568f986"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f342fa66aec5c630d64e489779f984ff996a3cca"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "477ce3849061496ab47dad27a86ac24f83a988204728eb345200d284cac3a6aa"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "1bd0a96c66f4b223efa6ce807213839b23419869"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "db3b5c5758a0137a74ae30b0c3fa41e88aff3288417afa3336d138e94c18c8c5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.1+0/HOHQMesh.v1.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
