[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "f0b47524d0ea83b024c4f6f249baf5f774886ab2"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "f7205dbb11cff1cef3e0190cd52044fbb1485231df63bc56dbdedc8ceff88301"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "83f72b45bdf724e41a9a281a65e2c5e00585542b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "e55c83ee02cb6c145ae598ce8ec30eef72524e0922a8fdfa16b7a2d96afa7399"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "a398bce2a8176da139b6c2f84cc4c2e0dce99205"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "41f8da6f9466f92475b792346e41f0df78be382cadb985f38ccd349a8a762adc"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "61aad2e5271362c39a1b5c38bca5dcd15c09554d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "4cb7a4c31e9be9a08cdca898d65adb53c81d652d6212e3cfdf00bca2f17f081e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ded89f43b2afa3c35065bf95feccb1abe95da740"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1522d82afe54fb8a42fa49d27835212be07513d2785c8fb615f38e956f82d1a5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "480c29db34710e9bf81183685a60eaf0585404d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "bbc93a805b54237124ea7e6be3b9a209c1df1f3fba56dd74438616710e547af7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e54aeaae13098adf5331db5cbe25aed7579eabbf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "40239664b49de3fff9e597c3dfa04a37d19b1a502c678891447be9df59c2394b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "acdd8a581cc7b41149a0039c575e653d1eacb886"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "066a1092e180cbab93c0de826c0aef2be74af5fde223527920a8b8d3fff5a23f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78f56b381e53e4b4d00486eb6b0673f097bc3830"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "d1e90fd5df9fdac7ce71ddd251a245b7f229d5e2df0d7f6a5b33ee5957d327af"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d29f9ba5942f5188929993fc939552883a9f4b1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9e69d9a9511d064ebdfc3f5666bde4eb8ffad4582d909d94b3951be88cf8e43c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "1e15af333d64bf3871186f25b2220c52874517c1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "247578a00ec1b11858336bec4a24b37aa6c8c3ebb8497511eb8561713cc23035"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "feefabb37cb140491d515940659ce2c0e404c0d2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6358602fff787116d60535fc27af51db1244ef0fee09b15cb3d3d0b7951d19cf"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "8690a52c8eeb5b0136d5b1dcc1f1a1cc58c0797d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "7d9e885031d174a2caeaa09b17e7be9bad4d4d0b014b4ac410a60c9990831e40"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "027dffea33d1047d17886abf77ea558bd739bdd8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1b94b0531f91ba322e7e8f88c6b999202cb01b78c90ea44f3ff80256e82589ea"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "02da284b6a717187048b53b4272ff3cbdc618b6a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "757dc0e975f3fcd37a6668e0b97cb17fcfafce9c6145e0249efbc2bf72c98fa2"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "13e06d1e8b5f783d181dbb4fa2e68a1b4b00fdbd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0ae9d77823183485fbe4ed6dd3c3c7f4be44ae633d95bef6f8407f1d1281d32c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "79a6828825b065d1b9f038462c7240ac0be40b2a"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "a8f51e5491296907b89f195b8cfb140bce1b91a1dd4bfa554b6370c4202f013d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "669cb3cb38a002c6c731fc89b9e6a6b6b450ab66"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "8c327ca6eeeaade5f9f2e0d0cd542771df5bc303b558ed4d545ca601329fcfa1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "66c976ce51247f56dc2cda1151fa4530492b6016"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "5eeee9f61e880a20c313bdf11da591bd32e7a24d6056c60d8f3a6bb1b1d40435"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "3118e3e0ae557703fc8cfdf3266bc9d1e789e809"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6c088104756df0e4ffe5ec6dc457d38226b64e3cdef73c0a06bc2848b9c2f9c8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "eefb67bfa00e499b14474b53e3a08c80875cba40"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "bc622f821efa4b27f03a99c586cde96d5d2d2320540199632f100d80315ca10c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "df002d8da846f04d8c20065f763cf52b95f8457e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "b1040097df53446fcdbb8fd9ec38a63311eb18b2824392cfca8ae79a61d917a5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "8184bdc851a5e81c2f38f11202c4ffabe6a0d5c9"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "5fdf9d483709bddc450bcba0e4a788b5e85a82e452dbce068013bd43b940d065"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "9ec89b1af1bdf909b5632d0d1fa43966775c62b2"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "d9549b2dc61ec6747afd7894503f6aed2f4d4fb6bb96382a656ec952af7276f4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "3f89dc362666c724711812b62a859694df0a3c87"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "ec30902663d20c37f8bf6fc2dfa33c0bfa83a424cd1d747751a1c634c88b7fa9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "fa56873ad68f68f302ac74318c59469e46f7455b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "59d0c3c980edcc528333b2d4658a35102c72dc91d1abc81c87dcd19ef13f9548"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "bb820f1cac60cb6dd31e2b3ccf7d713c17de79ac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "753a5948d075504ba1f6d177d5a74c20ddf256dbcfccb44489abaf72a85fe0b7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "b0986f47c239be58e905ec4a5d2c65e48d0bd738"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "cd2dd8c4cb58f75cbe37e89166a0a494169ac5eee32897b137a2e97671be23f8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "140c5aef5405128a2449eee50a7950e8b8a9fbb5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c28ae49725fcbc640d4ad0cfa9602dd2e1291d5c7310b0a7f16080dde7da99ab"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "7b02bcfbda332478a51820c7f4ec2f469fd492f4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a46f132d83bc68ed67a8deec4e5df0429fce476b3557cb05a02e9a84fd4160cc"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "fd5692bcfa2e7bde5e627589287e3709e5c9c4c4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "83dc9621c770e2e7123d2f69a370709a02de1e351788c241782aeae0849fe8ee"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "e3cbcf4ebfb4565a2d68b86b867a7720adb6bdfd"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "f10af543961f26f5e889eb850d850a14016024527f858513e4bf6b9ff0d3da0b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "70762d720616af7e0f3d51540c364364afc940c6"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "bb11187a8d7a38c56481edba6e3bc94d897ba65cfdc9f9009d45c61570da6a5c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "5bf1e441f7cc49030c73c96878fa4900fdbc4e61"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "5965f112e22d92e2b7ed46b5a30f9fe0fb33ccb11888aaea3c2047e1ca0056a7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "c7a70e64e0c0f39440d7682d1a2c8a18760a6abc"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "f87d9be9f2cc7ad5364771493d84a64655cdd4e8ce07ff5ae962ac4ceb135c25"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "ea0ec522589070f8f97a36856c4b63403dee9640"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "a5d79033cba4b67648cbdba057daf656247d9977d8664e1859a2895458e5d4b1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "00ad4bbe2d460f43c99241bf8e9fb95c175e9fef"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "880fb917848de842317fdd9c328ccb019b11cdd79fa28b476558eb620465671b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.0+0/HOHQMesh.v1.4.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
