[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "6eee7b4af4d01cd06f9964208641fafab80ea2e0"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "38f58648a45562cbd5f24b38e15c7ee26be20a724d51c27ad6233b6264fd2f38"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "954a76420a5e49212a488bb610c9191e1ffaa9e9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ffea94cb29e1fe5e72e27a695d855ddaf29781ec509824911430a444f0917dd7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "c262e2cd60c2deaec9446e78367ac58b3a901c89"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "7c32ab901b3ff12b891ea3380d1f2e9f6c279bf2b87d291897e9ffbe321f0e28"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "e2b39ba0e7a3014fd6c339dcc3ac9fd1afd1bcb3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a2bc4c961fc3161a588a078b9b6c3528b00939340745c2b3a957cf44228b009d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "697b9631764a8a2b4b5250c285d6796195c03c8c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "2b7b316772109db2741945db8adf445ab78523e100aaf71a12b009ad23b98e18"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ea1b217124b67fd9bad2ef6e873c2f2d24cb8a8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c75c8853bddf13d937e030862b7f3f2caa0392a7016071fe2b13a0f1d3105fb3"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb3a11989c83329e0148da1384d7a7d246987ef3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "aa4564bd5f45764b77e874acb5162cfb6b25b16e5b914766eff8a708339ebb8a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa601daf5e5ffc1f0b245dc269d5ef844a35fc04"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "192fe2001263b0c65f1af98ce0d827d78ea71e92f9f1fd064d9e71fe68cabdf0"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "698035c6ed17ae373131e4f5951e5a1a09ab428e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0d0a6c6b4520585540804f64c5ff3ff827c2feb1d843052eab253990ba5d2d2f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bdd58ae3df589120b33fd19879c2818cd60fd164"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "35b6a897b08c37568950e2d8528c1c6b04270f838cec1bbd1b4f766419467df7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "0c55cd9f98412dc85bf2b70e7ba860615f266bfa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0033f0ff78749982c313be68bd4d23d5d5f2ff7b6967875aa492776e2ff20272"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "655cb0dbd1394b67c86a01f65609dfeff6689b26"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c409d79dccaea712ccd3d1f664adf35d129e3b3f6f5296ee8dd157e4010959ed"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "ac9219dcd27d25d56abeac9f797e58d503c9b049"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c3bb59dff72c991601501283c937e6bf628f0170e0a324d09db6d6a28bf3cf23"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "c863e58519796d4419e85bf992301d122c26e5a8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "06179f422f7b7c7c8985b03b5aaf84bae5aa7ab030226808f559ca44c6fda82e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "a3b02ab6d6414f3e6827868112ef9046461ff6a2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0cb09d7a1dbd03f080d76f7c2074736009acacb76c68c37fee2104c29ba10649"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "c1730ae1918e7c853e123e2285e8d7888df3bd78"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "3aa0540070e9199952e044b048eae570fff0854c49b990364660e1406f448ffe"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "ddb78c7b25c8db0fccc88a1f38b43de9dc73b1b7"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "eab50ae42bfc943feeea01613a771cfe979a39ae537afd403b266b8a6d811af2"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "0defa46628c3e9002b268fa0ff79ff82689bb128"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "89c8be96219694e713a293610512c47734b4e7072d56e59cb964fa88bcc7cdd4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3f06a031a512875b19ccfbacfee04414dddcbe22"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "b8619f2ca48d8ec6d98897f8ec2bdb87fd1e09a11da6176e67a2313d0fd54057"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "24ecbf0eca0dd417b973b95e6e324dfdd3836b67"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c68d00430a3c018485e9bbe03faf9fe40216b6bc9f88007824601562c23405da"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "3ca340e88de7b68ec00e664fe6d3b6ffda7da514"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6b46d4aaddc47e829173f0720b909716c532782ee1cc895ca16f1fb2e11f7a3f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "f10b6ffbad9a4d7a3a745f3b7aacc36ac23f5cf4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c19e815d60c559ffe0c172834cb024121ad418b893e5edf548fa32e1fdd7398f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f616cb65f374e90b4c8d13774b85fcf2615f119b"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "f1191b6bef969c03ad0bd6093439080728f14e112f310fed7ae7b938c46afc39"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "da93f91cce4dc0f9ab76d73498042a2ff6cdc83a"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "0a80fed5bcc7fbb89d0a53e9d75025bb106c1d2965c20ed647f19ad2cad5c210"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f09e48f3f845dda3068414df0d63c6cc6ca396b5"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "3f825f8929c88722d06791832f2afb3d3e3906d92d637e5590e21420758e28de"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "3ea1d54ab640b3f4f4569d98e6b64fd1fc37234d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "50961f056e7d3a2015f0df1a0cdca15c2d66e8798f6b1a4ad50175ca469b410b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "455faed2a0ebf01a41c9e9a09b349dd7e2dd422a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "33bca3f519f58546e42ffbd31b999140a0e2b1693d4f40ea6f57d61524810b61"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "1265125a25a58033cec3d83c53a003f44e411cea"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "019192254b858dca66e980ee39223d31744927f77c464d31f5329a99e8c7b30c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "bca71437707cdce3f19fdac0e067228f9ca154c2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "29de9f9dbd2eb80f8a496c5cebe183078e7a521022b76d70a6858491cc99f2c9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "48d554c318cdbfe9a0b743de1bca4557851d30db"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "212f522ee1c0a553a5b871d5f98eb95841de1805b99852ce63b2a496525d60df"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "380726945212da6ca5941ebbb0b0e69409f8b2e8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f5f82f8793b87ee872826ad575e4e6aadfea8b73aa0eac0e9ed58a1cec27a251"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "ee37748dbbd4f59863f2e7dd3ab15628472a8689"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "7ab2d7e750f4dc8a29c668cef627625a27489a5e4c953665fdef77e84c0bbfa1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "a381298fafa9705313fa42ce1ff17f36ed73eb58"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "8140f20e44873a84c78f1e45201bcce99ff207a244f7d457e6113c513676cc48"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "1dd083e4e772eb30928abde215fa37aae1607c5a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "0e09998b698e0e79887a0ed9acc70afdf237a4ce8e711ab1f069553a6e462d2f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "4d4196f3c0e75f0c8b691550a03d84eed134c484"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "2306c0b76dd564bc973c08d76ad20ccab68bc127bd2b64110226c80b88b8bd54"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "c3c181848ac42019476d5ff9433b3163aae9724b"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "6daaea96178bc1e47a77ae21ad6e5870f7c1528b874825483e8c81887998c64d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "77b65f3f9d2089b466db77317fb1499677012708"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "8602a15f62ad427f0064f6b833c13f937c502fb6872cd164342ffa1258ad4427"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.1.0+0/HOHQMesh.v1.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
