[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "2aa224faffb5520f0834d767fada3f3d9edd83d8"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "bff3550305ebe597c6085127dbd2b4e15e70578de26b54057cea143528c65d91"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "b70d7e82029b413272873258467aafc8ab4edc7f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a85bb5cbce78eb07e318590aa072015931e1d8eb8d8e8081d9770defd27e3f89"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "36a0e6fcfa8483f69d2b3489357ef886db7656ca"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5264450995f934597d0a439e646ad979542905084a2b6377837c5a8def2c7feb"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "6cc5eba0bc65280cbc8c1c2d3f9051142b515698"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "81f01b76d41d161a5e7959f372d174247326e9fdb8320482e6e019c78d92b2d5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eceac2b880a2db27e8e34931e3682231aaec3ca9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "36d2059640a539c6027056e91c35990eb716433432379533c4ce5bd243344df4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c197386645b2ec8d30286c23717e88f38c32e2c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "925e532cf1447da2be013909fa92032e754f93f2748363b5f3510ce07c6bbad4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "74cf58e4eea01288620417908157d8dc3e2333a6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "47ba287e1b2ea82be0807f5e393c4680bed7f872e472060d24e031354296fa9b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bda5d641dcb52409b1a8f7355d35a8262889d88"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "fa52fdfbc4f668356c642d91690f32e52cf6a4deeedee21c74ca2c745431ecf6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d3a9eaae3674ce7a47f4aaa5a64c8a9497712b7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "b02aade4128010d1df3225a2af2d15f42528cb78fc1c5c4b3d4c6ab2596580a6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6a8e9c6c068e565e99b61abbe220cda6faa3c6e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f55591988aa18305b4ec0b0a33060f02e5bae36689dbe01a26b575cdde53bcdf"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "14649bc39d4d5c1de3c0828461679f91627e868c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "e41c07402b00c33181f9c0f3d930d8df2fc6c1170f91eeead2ac107bf0fd58ba"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "038be85582269d67e5d23d5054f216819de15d0a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "0115061c882cccfd67291510b817a7809121f159fefba3b873decb7c8ca10435"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "fbc784b4b65af50775984388f88b529c1bc69d09"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "4b61133e2670d052da6c881c4e6dd68669ce634e1573cae6254affc66ab17f6f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3ebc2c9fe263958188ea241767517f33f0510bda"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ba66d6aa5a0a83861afa3c5f591bdc63a6b62a431239fd0435e0bae93c217fe1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "267470719d1d955d29cc3564a96e825faab2e458"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c4d96277a662dc1d630ed90ef83dae590ff25ddb208775c74f9c380a6a0bb74b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "9afbb6cef355aab21e98251ebf664768c70c46b2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "2276efae7d197eba8c6b051ea69989f60418741137ce91aba13acfb863a504c9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "45126a68994dbe24304d11ee8cad9289a2a74ab9"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "17278bea8bdc3a507cf4d24141762da98b6c86a063c7438862db28f379550746"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "aea9cd9a6c256d69e5543225cd62ea7c2b6358db"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "cf00c9c987c6c0b29cbcacde59b0e3b89f0a52735ab44dcd2d6f4dee8c780268"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "763139a81263577f2638d6481f7d44970aaa7483"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "31db98757df7b68cf2461cc5fe15ce53fa4415801f6e93ee8cab80363ba575c7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "d53d34fdf57a7fa5753aaaeaf0967a47e72943ba"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "79c3c3c3e0e29d38d41791e750796addab5350c0c5db391038dfcafeb39d515a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "5d48dbdccf432aa13b09ea614d8347398320f397"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f563f38adf09705f906cffba917a64ee9b5b41496563f0e8f020a07834fa4a7a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "a223c6e9f32dbfe3f5d6eb8fd490b9aacfe7bdb9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "7e29ef2e4f849679a8c687933c3633b7fd2fd51ae68979c97fc574e10923ce74"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "63aa1376c06b6dfad26b2aa171c1f2a0847a8bcf"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "80f32555be8144d70f9b887acd0e1de4a6c8970dad3ea11c0d35f01ba4c4c0f1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "dfc1a5c6df307fe600799a7715694033c249e784"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "e390b9fbb746963c594d71fe055c8bfe2783b885ed4ed1b08543d121bdb0200e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "cd982cba4578b90886538f1f509e868cb045280f"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "7388cd1e5dadfca801f9523228c338849e2a7e763ffc71a73203eb8c818c63b7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "242a9b1632e230d776b9d34788775576de23dd01"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "bb3100c163984715428c922b0f499e25458acbf2d87fb8ee782acf2b3309732f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "25a83845fbb4c5ed5947749e3977337f5ed21553"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "892d7f6b9fb2171b70f292292b447dd32750f54bed1c0db70b01687af6f9b86d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "5fc1ad4f4ba2b392d6538b57aabbf119a0e9936e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9f8db86990b629a50645033a1baf89bfff61e835e97807fa24893fbcc5045811"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "14d0aaee0d177fa5d3da7b5226fc7740f582f5e3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "2f368a158908bc988f978f084c5f68dd8aa59f8e2d5e873b28d3ed0e6a926f16"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "91e6db98df28cb85cfe71f007e93e2b9a6f0126f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "033db1bacea5ffc5605d59dfc97b7e91d6bbb859b90569fd9150b869598e78c1"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "052e8c6529f190d41ff5baed9949df270e2abd8f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "ae43de07f36b85a14de19d3613c20a1bb22d05084db3f54eb4d5a87faccc4aff"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "75a2b2d84a1155657cda1bbc3dbd6c02f440943b"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "a09b22dd01ad911139b7ff5a6d48f3c3c883fd59136515e5b93955bf6bf446fe"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "b59c273e2b02a5dc6751774637031cfc914f6bc0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "359258b0cbea0031d86e8084bcf07fe9d76300cd9192f74ffc6d179cf450a050"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "3268015fd7df6052c47b9df54aa1a1070a84a66e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "7a183a4e958f31540f532c01b62beff8436629efae06315a255ef141231cf80b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "0a8702bc1b05be40f3fd9e22f12081bc287e9bf9"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "3618042efa3007d50867fc22657cd96c8bc79a668b316d4361d6ddfc187f7e04"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "e74cb1261f7ecbca01de42ebd2d2da28f4adfb39"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "d02f3da1bf80a63dbf637d2556cc81aa591cad703f3fb90b28f8178a12f11053"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "40c51fd17096d79493a31378565248a89ce2a62d"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "8c0902feaa63f3f0197a0cebf1afcb79225fa77187e42243a4f538bdf3134516"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.4.2+0/HOHQMesh.v1.4.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
