[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "926027d96ddd00d6ee20ad2a4df019edfa4e1a96"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "7b160459c4bb4facd68b0e7ed5de26125719f2f82d448dd5a4de825527b37844"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "b1bc2b9abe2be131406d0649ad0c9c944516a832"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "388c932410d5ee0bc22253c112f5ba6316bbc8191666af7aa7c837fc03a5c3a7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "3453e227ecd3991d37360bec37fbe6a9dd722120"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "d9f992dc7ea25c437605ac752c88500a8560b1e671ea520c0aaf580d205f7f81"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "d51caa5d038a62f54c2982e586ee40d47fc06176"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5de0e142c4e348d804791a221a77ceb1d7ebe6434878e6404d5f218c8931860b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3fa8deee0d1e5799a39d3b33d06f8904be2872a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "259534ec7931dc2f86e1afc55c8d77c4b327108af2c65f38ff9beb77ed373a9f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cfd35f1adfff2a3fdaa072cf10c77c2d61035fbe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "aa3b550ee521a3d7de6456a8d517ac8e079958fb654ad61e88f1f5922254a0ae"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f65fcc1e816280ab3e5a49ccebc259657b65ed27"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "8c66b893505959bbdd24095dbbdefc0d8ffa09c7b665a23a9a7a11199e5f4511"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f6e36781f14c925babee2793a52540646e86819"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "245956f5f4c1d509fb915bbd7c31e35b743fbf3518a3cf30119f82727adb5e99"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32251a79082a8eb652124da6ad7a41a3d2805aee"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "87ab0b3042f918d1b69267bac58d261a606d0f0a6288e56972d7dedf57bd5e1f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d372bca2c80d8a9503788643afdeba7e90d92eb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "fa2f71a10ea97f2d83a185fb83a2a5f6982e30a2958108ab2f6290a3df272b17"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "0594eb98f87ba4b1f42000ec22324c2185e00ccb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6a85df9135ad3da0b26d2bc8f4d9d9710cb597e40890fa0cf6873fe8795ca2e4"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "e0095f5a9ac2c78f0cfc58777b16e30b36761d84"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "475384f07b03b2b5d2368f0d9cf2f67ad1068795d193f90dab864cd3cbf0e676"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "d58b69b26def41554048872477a54edc00a9f90e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1052ccf00b334f930be884cdeed2e7ed4cd8ae4510c4d31ff638e284a71a8a69"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "e5303c4136c3174e66afa895dc7be69bbdb1e38e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "d34e2cb33c13401b3dba19995b6b2f12e4eda334ef34047c97f877db31e69a41"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "d368908d56cbcb16458754e0d0628a1e2b6db081"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "26224afafac728763b205fddb4d0d159854db2095c67c5028504f634123334d7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "87770d7786ce92309d5774a7e9f49eb29b7c3641"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "65de0b4ac8e1862cbccf422253ad47a165b283c01459f8a52c1fe0f87213ae76"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3f40934dcb17926ae38f72579c2624c9b4473984"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "6fd582c7987bac09c1890742886a93a1198d04c89f1d858a18b3aa9ef159e05d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "df18cd5504638ea196ff340f52e363d0538df98f"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "ba4b077684cb06f35190bae94404af347371d396a6603eea7838986b1225dc78"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "c9c1b4139bc6b36ee79ef97408f4056ff98b0b88"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "8976895f4bb3b3b6b421d0ec0463a4a6f917e0ea82251c6e0f47c5d8702040e7"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "bf174f3735634a1816b35a605541b511d2eeb13e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "cdd215af86c3e35fd553bb3aa9345c1fd3968f4f5e4ddb432499ffbb224e6240"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "0e488bdc0772e5b05eb2111ee237f15596fdb362"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "cca7b07be0ea17ad81e9b87315378c7511f997d4b4d6031e704798d28a0416c6"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "648dc456c339686a6ce9f049fb8baad19cb65354"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "fb3fa6c1d1f99bcec401b38322c8121010a01c2201aa706ea3539f30af295f7b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "fc44ea8cb333628e517a5d910a0fb3fdc68ca3f3"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "29d699bdc9f4ce78eaf43996fb082566d90961433108f6cd837253ebf3ae044f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "11356e827e50167743fbc6e426fafc79b4718688"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "81274a9220e55b36f5e24d7519d0c209ddfc41889ad01866b91a7afbf419a520"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "88d266b887f03799ee0fdc2e9bd73c1993aef0f5"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "7e57e3e9b87888893d194f4f64647852fbf40760b935e2c336127df5f678c3b0"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f68d316377e0861f017cbec82dcf8373b8dc2ac5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5bd672c28d2ec2da37ab90e1404dbe3dd885464664e5ad592349d2c888b3a17e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "3919f73d4891151bedc9a4cb1883fc22db3ec26e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "38553aa6b9600ab67ff81bf2db493d03b28bd9325f88379a8dd44d6b7618aaa8"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "56c3f7f5bbf5405b7c241a92352f96bf8a0a31fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "01e993564cb4cf2f58796048546137c58c00d29a01bf47799a9f64ef853636f3"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "dc319d4f6fb00f4a6374e81497ffd2e82cd58b7c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "d677d32f89eb15ea74a9081a819295f2575948b0cdb08e05047af4548c58fe69"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f593a9e44afce06444050500fc02b586e8dab2b4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "6850d7afa322cccbec6757921edb1f7b275e48797a33003a3d210538db8026b9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "eed4367b5c23c8ada5e857d0a00fc2c2ed524201"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "c032b55ceb28dc7e51a30af2ec1619c660b6e1703a1f91807fecee29297fd49d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "cf08b9d2c3e858e9ac0aeb791ffb635b9243a55f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "d5f716b4fac7ccc3d2c1fcecd07e4be2f7d85be50bc9dc5d271ad89b5d714a6d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "80f9bdfb48285b8f3c2455cc323207db42bfd0f0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "c924fef9c5474bd022df8bd44423951bfb55bcacd8f39604a5d9ddf107629f6f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "e9c7bd617c718da066e6b7e3e541ea3057c3c076"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "526690f0b0fbe8f28499a8a8ba03b4d972005a3404ffcd748c127189cb2d1df5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "af791ad1e353ea2e8bc6426687126e238e8c9f0f"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "bacb77eba8349ac9f9af429027959ced6fc0dc66b3f0ad1378b3ab120a5a961c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "56494782fd3b392591777f53ffba4ab2bdbbb948"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "fd495ea37d8318a14f3088839a86cd04faa84681d0508d13740e08b5cdbacfe0"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "651711f38b76920c54266b342fbad8f70ed0f30d"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "dd843d9ae42cb03ebe67bdcae1ad9b0807a61e6d3315210bac0f00dc89db33de"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.0.1+0/HOHQMesh.v1.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
