[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "35b33cb2166f2d1269fba4c26bba5149c93e35d8"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "fe5876f4e7a4d417be19220972144236ad35e93a7b40b972eec8b4a4d2f5735f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "ae56343672355ce2443bbb3caccef8122254744e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9f0e5e6116e9d273abfaa512a468b0e0c8d40670d452e3afdb4cfdb94404b533"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "2326afca200211972ebe96bc91973d1286a5fc4a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "5b305842cded7d141e590ed01f177de96413b8740d8bb05563da05e5fb9a8fd9"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "aarch64"
git-tree-sha1 = "d0adc229ebcef598fc05688a2a887cc56995ed8e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "e6fe48809f0f62245d4f758f769526cfbb810e61c26ba378888036fe9ec5fb1a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af8051003020cb8d5559331b299e1908c1351856"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "80db6071a4752b5811e48610dc2a1c8769b9a7e6a9707860f0fc12cb931e552a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df42749e0a354bfbca12bd7b0c7a6b55e02653dc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "af12b9900eb2c2e5df8fc6e0fb5613326c9c2f897f70060c0287a64e1f93a131"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23c20eeadf15bf75cc1eaf70aa6f53f4f2e71cdf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "2552df7603d73810e2bf26be109d723cf5b6eb3566994e94d76d7d96f7be0fda"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7cdd10738d518dfcadc4acb5b0ef9688c7376af3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "1d563cf20b39e7ce2310e3c204f4c89b65bd58311ee82abf11549118963d375d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f66138f7ee566027c0808ce6e68f8e144e31f42"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "393d68e9d566ee4805461c3eb6b13a5572698be5dca29849a6858e4c09ab0e4e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63d097d07ee06270c79218b1d7b7ecbba97a66a9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9204c1e75a858cefae4a030053669d72d76e6c709b6d1dbe5f29e1e2590c5d3a"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "8c7e0f68c4e5cd66c5593d853682ad5f54fea5d2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "92d32da464bb18fb0e9de2a4db58e52d4a89a7d69f606eed8b033fd22926caef"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "f3a7cb0130c03184b17c18860081fa727bbcad08"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "7d1925bdbd6340c23883d611fd1023e4fae56ff7cb795881c99dcc55acd81cac"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3638bf39e5ccfe3e02b1b00aca95a703d8c5c9bf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "f0f004f68d4cd6afb86769bc4e8e9e3bccea83fd9e4d512d11710d25b964758c"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "3bf8e20877cadc1523a7aaaad89f98210c2df878"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "08c7337ed492bb3a2371babe52821d1ba6931c28bac48dad69c675464a58f5af"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "41298c01d57d71c5369327ce216394d95b483060"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "a6cd5fd23b0cd1f76d90d9e8ca64d0a54653454462d485cc2817369aaa8081d2"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "f2ef2d11165a08aec20f65638af0f2918a38feff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "426ac96b3518d7ed3271ff218e88874036e6795aac1701614309d7095c233e91"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "1db7fa034f324ea1c1c388b02754af849e712d29"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "c3bee6482ac68499fd3c7eede85f2dd30774b5e3fa81b4370f08a8e477fc1bb5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "b61e672742c1e9fa13af1257d5a15b419ebb9984"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "2866882071a05e4eeaed38efefb8bfce0f9c8f4f09d8994ced752c6686e6c163"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "i686"
git-tree-sha1 = "4d2619a3b87c389edf97257bbfc39eb9a1ae2d05"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "2068cfb76973fb551d73d36b8dcff41e55a4626420dc520529d3322a6720535b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "5a57c59523842f1f479598351f04558347719ebc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "08ec105ecc7d15fdf95177821f6dd151a0f590ddbc903d122d0c9d8dad27b787"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "fc8034b4ac74c44ce3a5a392a70bb3922366a4d9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "72261e215662185e65d3d20f8e7ca9398489fdf028a1299fea792cc8fcc71be5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "powerpc64le"
git-tree-sha1 = "93c0ccbbd46f5f2b52b3f75055dc7dacf5927360"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "b57a293c093f389122572b7dae2ae4becf1da34a8ff1bdb501b470d5a7f21f06"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "4f71ad41e29b48e912df828a22d16d41d76b1367"
libgfortran_version = "3.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "2edb239a5e02d5d9e963ecfd0d8a9c1aa3720e0ad9d6029dfbd34bec284f6306"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "50c8f09b96b9ac7e65b97f12122208c5cbbae92e"
libgfortran_version = "4.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "13eba1cbf39d5b1c277fd50c6b0102681da7127cdc7f8801a61206bd1ca7a9ab"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "deb3cb65b3e81bb029ce5a24bb78ace58e42846b"
libgfortran_version = "5.0.0"
os = "macos"

    [[HOHQMesh.download]]
    sha256 = "836a49916f752516e0b6ef140976290bbc5ef39e042e5434b596f9ac24c5812d"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "af99ec96c83d6463bbced3144dca53138277fb44"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "9bdce253312bb6608b7a85ce175fd8d9885fa58636374721ae483fe6cbdba1ce"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "33271230f7d76ecde92d6376f20235ac35214779"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "fd6a392ede8e9c5d0048a587ba49aa1fa2beb6570271f5ff07068b412e7445e5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "cf8e74c5e6b8e1dcf7317e363fcedddfe91c2d5c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "93d1996e3c4524bdb0ca481d8d858573cbfae4550b76a191db2a38a53ffa752b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "23979aa6b40381b9a8ac15fc868d69488a9752a7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "8c14cb4a5e81c66c86cb74ccd2f35be05d33cd990012fbcff698afcb07b8279b"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "25fad9003da013f3344c0d21d4b8e9775f4b6f52"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "90b6b45d0c2c7e3fbfb39d2dd045e01323db3db9a88d36ca37b66ef2ad23d1ce"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f5b8e01c2a7408f9817d2c28c30a6351e6b56ee8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HOHQMesh.download]]
    sha256 = "4da173b39c47f3c309300a2e8f3ccff1107e6959af5e4ffd752aa12ff3c47120"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "6181513f5ddfd482e7b42b93b7a77b53084c4214"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "410fff13dd79f370669b1231d5d6cb34f7596365688abac8de4af1987eefebf5"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "d48d6235c9f4d8dba16972312788eebbcbb39693"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "7a899b2a0a327a8c34bfbc00ddc5b366cb744fa210a82de2194c48c4c37f3a58"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "9eac201d65ba56fdd14dae0516d58684ae87f362"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HOHQMesh.download]]
    sha256 = "57b2882621892643ea83c02e9ca54d4900d5a6781c0e26f2446e969a24609829"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "fe12ae067c25991d869e0254e459605b8474cb1e"
libgfortran_version = "3.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "4a2877e1447dab642db55f4fd6c8f0b08da561a70ea247f2031801870500a709"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "7003b55c6f71c404bfbfbb0c40aa77ec1531fb03"
libgfortran_version = "4.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "e1022b3c8079b3e6c890a9c268f7caa520a332db77bb719bdb5eb1d403158d7e"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HOHQMesh]]
arch = "x86_64"
git-tree-sha1 = "f7e9b856b3ce9e6b40102b37112b2d0cb818f337"
libgfortran_version = "5.0.0"
os = "windows"

    [[HOHQMesh.download]]
    sha256 = "b887364a696d42907c3dfe3fba87fe90e799fc820d3aea123e3a422f7ea0996f"
    url = "https://github.com/JuliaBinaryWrappers/HOHQMesh_jll.jl/releases/download/HOHQMesh-v1.5.0+0/HOHQMesh.v1.5.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
